### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by ahmetb** [jamiehannaford/what-happens-when-k8s#3]
> How does the apiserver authenticate requests? When the server first starts, it looks at all the CLI flags the user provided and assembles a list of suitable authenticators. Let's take an example: if a --client-ca-file has been passed in, it appends the x509 authenticator; if it sees --token-auth-file provided, it appends the token authenticator to the list. Every time a request is received, it is run through the authenticator chain until one succeeds:

all links in this paragraph are broken

**Comment by jamiehannaford** [comment]
Now fixed
